/**
 * The JMdict slice this repo can commit, and the citation check that reads it.
 *
 * CLAUDE.md requires a source citation on Japanese content, and the content
 * carries them as "JMdict seq NNNNNNN" in notes and in file headers. Until now
 * nothing checked that a cited number pointed at anything at all, because the
 * dictionary it would be checked against is a 122 MB download: gitignored with
 * the rest of server/data, and over GitHub's 100 MB hard push limit, so CI has
 * never had a copy and never could.
 *
 * Committing a slice of it fixes that. Entry number plus every kanji and kana
 * spelling, for all 217,076 entries, is 10.9 MB on disk and 4.0 MB as a git
 * object -- it is text, so it compresses, and a later version stores as a diff
 * rather than a second full copy. It parses in 118 ms where the full file takes
 * 1.2 s and 577 MB of heap, and it holds everything a citation check reads.
 *
 * Zipping the source instead was the other candidate and is worse on both
 * counts: 13.3 MB that git stores at full size, because a zip is already
 * compressed and deltas against nothing, plus the cost of unzipping 122 MB on
 * every run to read two fields per entry.
 *
 * The 122 MB source stays local and stays ignored. `build` regenerates the
 * slice from it when JMdict moves.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "server/data/jmdict-examples-eng-3.6.2.json");
const INDEX = join(ROOT, "data/jmdict-index.json");

/** Content directories whose entries can cite a dictionary entry. */
const DIRS = ["vocabulary", "phrases", "grammar", "lessons"];

/**
 * A citation, however it is written. The content says "JMdict seq 1497610",
 * "seq 1070510" mid-sentence, and "sequence numbers inline" in headers, so the
 * number is what anchors the match rather than any one phrasing.
 */
const CITATION = /(?:seq|sequence)\s*#?\s*(\d{7})/g;

/** Entries in a sentence-shaped directory are cited by what they contain. */
const SENTENCES = new Set(["phrases", "lessons", "grammar"]);

export function buildIndex() {
  if (!existsSync(SOURCE)) {
    throw new Error(
      `${SOURCE} is missing. It is gitignored by design -- download JMdict for ` +
        `Applications (eng, with examples) and unzip it there before building.`,
    );
  }
  const raw = JSON.parse(readFileSync(SOURCE, "utf8"));
  const entries = {};
  for (const e of raw.words) {
    entries[e.id] = [...e.kanji, ...e.kana].map((k) => k.text);
  }
  return {
    // JSON takes no comments and this file is redistributed, so the attribution
    // CC BY 4.0 requires travels inside it.
    source: "JMdict for Applications, English edition with examples",
    license: "CC BY 4.0",
    attribution: "Electronic Dictionary Research and Development Group",
    note: "Generated by `pnpm jmdict build` from the full download. Do not edit.",
    version: raw.version,
    dictDate: raw.dictDate,
    entries,
  };
}

let cached = null;
export function loadIndex() {
  if (cached === null) cached = JSON.parse(readFileSync(INDEX, "utf8"));
  return cached;
}

/**
 * The strings worth looking for when asking whether a sentence uses a word.
 *
 * Japanese inflects, so a sentence quoting せびる writes せびろう and a sentence
 * quoting とする writes としても. searchStem() in jlpt.mjs is the repo's answer to
 * this and deliberately does not help here: it trims okurigana off a kanji stem
 * and returns a kana-only word untouched, which is every word this misses.
 *
 * So trim one kana off the end -- for a godan verb that is exactly the mora
 * that changes -- and handle する separately, because it is irregular and the
 * shortened stem し is what appears in と-clauses.
 */
export function spellings(form) {
  const out = [form];
  if (form.length > 2 && form.endsWith("する")) out.push(`${form.slice(0, -2)}し`);
  if (form.length > 1 && /[ぁ-ゖァ-ヺ]$/.test(form)) out.push(form.slice(0, -1));
  return out;
}

/**
 * Every citation in the content, with the entry it sits on.
 *
 * Line-based rather than parsed, for the reason manifest.mjs gives and one
 * more: citations live in `notes:` and `grammarNote:` but also in the `#`
 * headers that carry a whole file's provenance, and a YAML parser drops those.
 *
 * `item` is the live object for the enclosing entry, so a citation written
 * above the japanese it belongs to still sees it once the block closes.
 */
export function citations() {
  const out = [];
  for (const dir of DIRS) {
    const path = join(ROOT, "src/content", dir);
    if (!existsSync(path)) continue;
    for (const file of readdirSync(path).filter((f) => f.endsWith(".yaml")).sort()) {
      let cur = null;
      const lines = readFileSync(join(path, file), "utf8").split("\n");
      lines.forEach((line, i) => {
        const id = line.match(/^-\s+id:\s*(\S+)/);
        if (id) cur = { id: id[1] };
        else if (cur !== null) {
          // Two spaces exactly: a nested example block's own `japanese:` must
          // not overwrite the entry it is an example of.
          const jp = line.match(/^ {2}japanese: *(.+?) *$/);
          const rd = line.match(/^ {2}reading: *(.+?) *$/);
          if (jp) cur.japanese = jp[1].replace(/^"|"$/g, "");
          if (rd) cur.reading = rd[1].replace(/^"|"$/g, "");
        }
        for (const m of line.matchAll(CITATION)) {
          out.push({ file: `src/content/${dir}/${file}`, line: i + 1, dir, item: cur });
          out[out.length - 1].seq = m[1];
        }
      });
    }
  }
  return out;
}

/**
 * Does this dictionary entry account for this item?
 *
 * A word is the entry, so it has to match a spelling outright. A sentence
 * merely uses the word, so it has to contain one -- inflected, which is what
 * spellings() is for.
 */
function accountsFor(forms, want, dir) {
  return SENTENCES.has(dir)
    ? forms.some((f) => spellings(f).some((s) => want.some((w) => w.includes(s))))
    : forms.some((f) => want.includes(f));
}

/**
 * Citations that do not hold up, as readable lines.
 *
 * Two questions, and they are not the same one. Does the number name a real
 * dictionary entry -- which is what catches an invented citation. And is the
 * item's own word cited anywhere on it -- which is what catches a citation
 * copied off the line above.
 *
 * The second is asked of the entry, not of each citation, because a good note
 * cites more than its headword: ステーキ cites itself and then ステッキ to say
 * which one is the walking stick, 預ける cites the 預かる that pairs with it.
 * Those are the notes worth writing. What cannot happen is an entry whose only
 * citations are all about some other word.
 */
export function check(list = citations()) {
  const { entries } = loadIndex();
  const bad = [];
  const byItem = new Map();

  for (const c of list) {
    const forms = entries[c.seq];
    if (forms === undefined) {
      bad.push(`${c.file}:${c.line}: seq ${c.seq} is not a JMdict entry`);
      continue;
    }
    const want = [c.item?.japanese, c.item?.reading].filter(Boolean);
    // A file-header citation belongs to no single entry. Its number was still
    // checked above, which is the half of it that can be checked at all.
    if (want.length === 0) continue;

    const key = `${c.file}#${c.item.id}`;
    const seen = byItem.get(key) ?? { ...c, want, matched: false, seqs: [] };
    seen.matched ||= accountsFor(forms, want, c.dir);
    seen.seqs.push(c.seq);
    byItem.set(key, seen);
  }

  for (const item of byItem.values()) {
    if (item.matched) continue;
    bad.push(
      `${item.file}:${item.line}: ${item.want[0]} cites ${item.seqs.join(", ")}, none of them its own entry`,
    );
  }
  return bad;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const cmd = process.argv[2];
  if (cmd === "build") {
    const index = buildIndex();
    writeFileSync(INDEX, JSON.stringify(index));
    const mb = (readFileSync(INDEX).length / 1024 / 1024).toFixed(1);
    console.log(`${INDEX}: ${Object.keys(index.entries).length} entries, ${mb} MB (JMdict ${index.version})`);
  } else if (cmd === "check") {
    const bad = check();
    const total = citations().length;
    for (const line of bad) console.log(line);
    console.log(`${total} citations, ${bad.length} bad`);
    process.exitCode = bad.length === 0 ? 0 : 1;
  } else {
    console.log("usage: node scripts/jmdict.mjs build|check");
    process.exitCode = 1;
  }
}
