#!/usr/bin/env node
/**
 * Kanji content generator (docs/superpowers/specs/2026-08-24-kanji-in-the-ladder-design.md).
 *
 *   node scripts/kanji.mjs build   fetch KANJIDIC2 -> src/content/kanji/kanji.yaml
 *
 * Scope is derived: every character in every lesson's `kanji:` array, and
 * nothing else. Rerun after any lesson adds or drops a character —
 * src/content/kanji/scope.test.ts fails if you forget.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/content/kanji/kanji.yaml");
const API = "https://kanjiapi.dev/v1/kanji";
const BATCH = 20;
const DELAY_MS = 300;

/** Every character any lesson introduces, in first-taught order. */
function taughtCharacters() {
  const dir = join(ROOT, "src/content/lessons");
  const seen = new Set();
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".yaml")).sort()) {
    const text = readFileSync(join(dir, f), "utf8");
    let inKanji = false;
    for (const line of text.split("\n")) {
      if (/^ {2}kanji:\s*$/.test(line)) { inKanji = true; continue; }
      const item = line.match(/^ {4}- (.+?)\s*$/);
      if (inKanji && item) { seen.add(item[1]); continue; }
      if (!/^\s*$/.test(line)) inKanji = false;
    }
  }
  return [...seen];
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchOne(character) {
  const res = await fetch(`${API}/${encodeURIComponent(character)}`);
  if (!res.ok) throw new Error(`${character}: HTTP ${res.status}`);
  return res.json();
}

/** YAML string quoting: only what this data can actually contain. */
function q(s) {
  return `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

async function build() {
  const characters = taughtCharacters();
  if (characters.length === 0) throw new Error("no kanji found in src/content/lessons — refusing to write an empty file");
  console.log(`building ${characters.length} kanji`);

  const entries = [];
  for (let i = 0; i < characters.length; i += BATCH) {
    const batch = characters.slice(i, i + BATCH);
    const details = await Promise.all(batch.map(fetchOne));
    for (const d of details) {
      entries.push({
        character: d.kanji,
        meanings: d.meanings.slice(0, 4),
        allMeanings: d.meanings,
        on: d.on_readings,
        kun: d.kun_readings,
        strokes: d.stroke_count ?? null,
      });
    }
    process.stdout.write(`  ${Math.min(i + BATCH, characters.length)}/${characters.length}\n`);
    if (i + BATCH < characters.length) await sleep(DELAY_MS);
  }

  const lines = [
    "# Generated by `node scripts/kanji.mjs build`. Do not edit.",
    "# Source: KANJIDIC2 via kanjiapi.dev. KANJIDIC2 is CC BY-SA 4.0,",
    "# (c) Electronic Dictionary Research and Development Group.",
    "",
  ];
  for (const e of entries) {
    lines.push(`- character: ${q(e.character)}`);
    lines.push(`  meanings: [${e.meanings.map(q).join(", ")}]`);
    lines.push(`  allMeanings: [${e.allMeanings.map(q).join(", ")}]`);
    lines.push(`  on: [${e.on.map(q).join(", ")}]`);
    lines.push(`  kun: [${e.kun.map(q).join(", ")}]`);
    lines.push(`  strokes: ${e.strokes === null ? "null" : e.strokes}`);
  }
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join("\n") + "\n");
  console.log(`wrote ${entries.length} entries to src/content/kanji/kanji.yaml`);
}

const cmd = process.argv[2];
if (cmd === "build") await build();
else if (cmd !== undefined) { console.error(`unknown command: ${cmd}`); process.exit(1); }
