#!/usr/bin/env node
/**
 * Kanji content generator (docs/superpowers/specs/2026-08-24-kanji-in-the-ladder-design.md).
 *
 *   node scripts/kanji.mjs build        fetch KANJIDIC2 -> src/content/kanji/kanji.yaml
 *   node scripts/kanji.mjs decompose   fetch KRADFILE -> src/content/kanji/decomposition.json
 *   node scripts/kanji.mjs gaps        advisory report on the decomposition
 *
 * Scope is derived: every character in every lesson's `kanji:` array, and
 * nothing else. Rerun after any lesson adds or drops a character —
 * src/content/kanji/scope.test.ts fails if you forget.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/content/kanji/kanji.yaml");
const API = "https://kanjiapi.dev/v1/kanji";
const BATCH = 20;
const DELAY_MS = 300;

/**
 * Every lesson that lists kanji, as `{ order, kanji }`, in filename order.
 * A top-level `- id:` starts a new lesson, so `order:` and `kanji:` are bound
 * to the right lesson whichever comes first in the file.
 */
function lessonKanji() {
  const dir = join(ROOT, "src/content/lessons");
  const lessons = [];
  let current = null;
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".yaml")).sort()) {
    const text = readFileSync(join(dir, f), "utf8");
    let inKanji = false;
    for (const line of text.split("\n")) {
      if (/^- id:/.test(line)) { current = { order: Infinity, kanji: [] }; lessons.push(current); inKanji = false; continue; }
      const order = line.match(/^ {2}order:\s*(\d+)\s*$/);
      if (order !== null && current !== null) { current.order = Number(order[1]); inKanji = false; continue; }
      if (/^ {2}kanji:\s*$/.test(line)) { inKanji = true; continue; }
      const item = line.match(/^ {4}- (.+?)\s*$/);
      if (inKanji && item && current !== null) { current.kanji.push(item[1]); continue; }
      if (!/^\s*$/.test(line)) inKanji = false;
    }
  }
  return lessons;
}

/**
 * Every character any lesson introduces, in filename order. This is what the
 * generators write with, and their output ordering must not churn — the
 * `build` and `decompose` files are diffed on regeneration.
 */
function taughtCharacters() {
  return [...new Set(lessonKanji().flatMap((l) => l.kanji))];
}

/**
 * The lessons in the order a learner actually walks them. Filename order is
 * not lesson order: n5.yaml holds orders 1-3 but sorts last, because "-"
 * (0x2D) sorts before "." (0x2E). Anything reasoning about what is known
 * *yet* must use this, not taughtCharacters().
 */
function lessonsInOrder() {
  return [...lessonKanji()].sort((a, b) => a.order - b.order);
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchOne(character) {
  const res = await fetch(`${API}/${encodeURIComponent(character)}`);
  if (!res.ok) throw new Error(`${character}: HTTP ${res.status}`);
  return res.json();
}

/** YAML string quoting: only what this data can actually contain. */
function q(s) {
  return `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

async function build() {
  const characters = taughtCharacters();
  if (characters.length === 0) throw new Error("no kanji found in src/content/lessons — refusing to write an empty file");
  console.log(`building ${characters.length} kanji`);

  const entries = [];
  for (let i = 0; i < characters.length; i += BATCH) {
    const batch = characters.slice(i, i + BATCH);
    const details = await Promise.all(batch.map(fetchOne));
    for (const d of details) {
      entries.push({
        character: d.kanji,
        meanings: d.meanings.slice(0, 4),
        allMeanings: d.meanings,
        on: d.on_readings,
        kun: d.kun_readings,
        strokes: d.stroke_count ?? null,
      });
    }
    process.stdout.write(`  ${Math.min(i + BATCH, characters.length)}/${characters.length}\n`);
    if (i + BATCH < characters.length) await sleep(DELAY_MS);
  }

  const lines = [
    "# Generated by `node scripts/kanji.mjs build`. Do not edit.",
    "# Source: KANJIDIC2 via kanjiapi.dev. KANJIDIC2 is CC BY-SA 4.0,",
    "# (c) Electronic Dictionary Research and Development Group.",
    "",
  ];
  for (const e of entries) {
    lines.push(`- character: ${q(e.character)}`);
    lines.push(`  meanings: [${e.meanings.map(q).join(", ")}]`);
    lines.push(`  allMeanings: [${e.allMeanings.map(q).join(", ")}]`);
    lines.push(`  on: [${e.on.map(q).join(", ")}]`);
    lines.push(`  kun: [${e.kun.map(q).join(", ")}]`);
    lines.push(`  strokes: ${e.strokes === null ? "null" : e.strokes}`);
  }
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join("\n") + "\n");
  console.log(`wrote ${entries.length} entries to src/content/kanji/kanji.yaml`);
}

const KRAD = "https://raw.githubusercontent.com/hoffmannjp/krad-unicode/master/krad.json";

// Both filter tables live in src/content/kanji/filters.json, because
// decomposition.test.ts guards them and a table copied into two files gets
// edited in one. The reasoning stays here, next to where it is applied.
//
// Stand-ins are glyphs krad-unicode borrows for elements it has no codepoint
// for. 乞 stands for the unencoded 𠂉 (the slant over a level stroke atop 矢,
// 竹 and 攵) and appears in 14 of our kanji, none of which contain 乞 "beg";
// 隶 stands for 彔 in 緑. Rendering either would name a piece the kanji does
// not contain, and a learner would build a memory on it. Dropping them loses
// a true part of the kanji, which is better than showing a false one.
//
// Per-kanji drops are elements that are right for other kanji but wrong for
// one host, so global exclusion would break the legitimate uses:
//   母 -> 毋   real in 毎 and 海, but it is 母's whole row: "mother is 毋".
//   杯 -> ⺭   real in 社, but 杯 is 木 + 不 and has no altar in it.
//   口 -> 囗   the same square at two sizes (U+53E3, U+56D7), one drawn
//              larger than the other and indistinguishable at caption size.
//              囗 stays legitimate in 国, 四 and 困.
//   八 -> ハ   krad-unicode names 八's own shape with the katakana glyph, so
//              the card read "ハ two strokes apart, the shape of 八".
// The codepoint check below catches only a literal self-reference; these two
// are the same shape at a different codepoint, so they drop by name.
const FILTERS = JSON.parse(readFileSync(join(ROOT, "src/content/kanji/filters.json"), "utf8"));
const STAND_INS = new Set(FILTERS.standIns);
const PER_KANJI_DROP = FILTERS.perKanjiDrop;
const DECOMP_OUT = join(ROOT, "src/content/kanji/decomposition.json");

async function decompose() {
  const characters = taughtCharacters();
  if (characters.length === 0) throw new Error("no kanji found in src/content/lessons — refusing to write an empty file");

  const res = await fetch(KRAD);
  if (!res.ok) throw new Error(`KRADFILE fetch failed: HTTP ${res.status}`);
  const raw = await res.json();
  const byLiteral = new Map(raw.map((e) => [e.literal, e.components]));

  const map = {};
  const missing = [];
  for (const c of characters) {
    const parts = byLiteral.get(c);
    if (parts === undefined) { missing.push(c); continue; }
    // Drop self-reference: KRADFILE gives 水 -> ["水"], and "水 is made of 水"
    // is noise. Such kanji end up with an empty list and render no row. The
    // stand-in glyphs above go the same way.
    const dropped = PER_KANJI_DROP[c] ?? [];
    map[c] = parts.filter((p) => p !== c && !STAND_INS.has(p) && !dropped.includes(p));
  }
  if (missing.length > 0) throw new Error(`not in KRADFILE: ${missing.join(" ")}`);

  // BY-SA 3.0 s3(b) requires an adaptation to say it is one, and the
  // immediate source is the krad-unicode conversion, whose LICENSE is 3.0
  // Unported -- not the 4.0 the upstream EDRDG page offers. s4(b) permits
  // licensing the adaptation under a later version, which is what the
  // outbound grant does, so a downstream reader has one licence to read.
  const out = {
    _source:
      "KRADFILE, (c) James William Breen and The Electronic Dictionary Research and Development Group, " +
      "https://www.edrdg.org/krad/kradinf.html, via the Unicode conversion krad-unicode by hoffmannjp " +
      "(https://github.com/hoffmannjp/krad-unicode)",
    _licence:
      "Source licensed CC BY-SA 3.0 Unported (https://creativecommons.org/licenses/by-sa/3.0/). " +
      "This table is a modified adaptation, offered under CC BY-SA 4.0 " +
      "(https://creativecommons.org/licenses/by-sa/4.0/) as BY-SA 3.0 section 4(b) permits.",
    _modifications:
      "Scoped to the characters this course teaches; self-references dropped; krad-unicode stand-in " +
      "glyphs dropped; per-kanji spurious elements dropped (see src/content/kanji/filters.json).",
    map,
  };
  writeFileSync(DECOMP_OUT, JSON.stringify(out, null, 2) + "\n");

  const comps = new Set(Object.values(map).flat());
  const empty = Object.values(map).filter((v) => v.length === 0).length;
  console.log(`wrote ${Object.keys(map).length} entries to src/content/kanji/decomposition.json`);
  console.log(`  ${comps.size} distinct components, ${empty} kanji with no component row`);
}

/**
 * Advisory report for an author. Never exits non-zero: a lesson introducing a
 * kanji whose shapes are all new is a legitimate authoring choice, and
 * components never reorder lessons (spec decision 4).
 */
async function gaps() {
  const decomp = JSON.parse(readFileSync(DECOMP_OUT, "utf8")).map;
  const taught = new Set(Object.keys(decomp));

  console.log("# Kanji whose components are all new at introduction\n");
  const introduced = new Set();
  const seen = new Set();
  const met = new Set();
  for (const lesson of lessonsInOrder()) {
    // Snapshot per lesson, exactly as src/content/kanji/pieces.ts does: a
    // lesson's intro cards are all on screen at once, so a kanji introduced
    // beside this one is not something the learner already knows. Counting
    // it would hide the gap the report exists to show.
    const knownSeen = new Set(seen);
    const knownMet = new Set(met);
    for (const c of lesson.kanji) {
      const parts = decomp[c] ?? [];
      // First introduction only -- fifteen characters are listed twice.
      if (!introduced.has(c)) {
        const known = parts.filter((p) => knownSeen.has(p) || knownMet.has(p));
        if (parts.length > 0 && known.length === 0) console.log(`  ${c} — ${parts.join(" ")}`);
        introduced.add(c);
      }
      seen.add(c);
      for (const p of parts) met.add(p);
    }
  }

  console.log("\n# Decompositions worth an author's eye\n");
  for (const [c, parts] of Object.entries(decomp)) {
    // KRADFILE is built for radical lookup, not teaching. Long lists and
    // near-duplicate parts (母 beside 毋) are where it misleads.
    if (parts.length >= 5) console.log(`  ${c} — ${parts.length} parts: ${parts.join(" ")}`);
  }

  const used = new Set(Object.values(decomp).flat());
  console.log(`\n# Totals\n`);
  console.log(`  ${taught.size} kanji, ${used.size} distinct components`);
  console.log(`  ${[...used].filter((g) => taught.has(g)).length} components are themselves taught kanji`);
  console.log(`  ${Object.values(decomp).filter((v) => v.length === 0).length} kanji render no component row`);
}

const cmd = process.argv[2];
if (cmd === "build") await build();
else if (cmd === "decompose") await decompose();
else if (cmd === "gaps") await gaps();
else { console.error(`usage: kanji.mjs build|decompose|gaps`); process.exit(1); }
