#!/usr/bin/env node
/**
 * Kanji content generator (docs/superpowers/specs/2026-08-24-kanji-in-the-ladder-design.md).
 *
 *   node scripts/kanji.mjs build        fetch KANJIDIC2 -> src/content/kanji/kanji.yaml
 *   node scripts/kanji.mjs decompose   fetch KRADFILE -> src/content/kanji/decomposition.json
 *   node scripts/kanji.mjs gaps        advisory report on the decomposition
 *
 * Scope is derived: every character in every lesson's `kanji:` array, and
 * nothing else. Rerun after any lesson adds or drops a character —
 * src/content/kanji/scope.test.ts fails if you forget.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/content/kanji/kanji.yaml");
const API = "https://kanjiapi.dev/v1/kanji";
const BATCH = 20;
const DELAY_MS = 300;

/** Every character any lesson introduces, in first-taught order. */
function taughtCharacters() {
  const dir = join(ROOT, "src/content/lessons");
  const seen = new Set();
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".yaml")).sort()) {
    const text = readFileSync(join(dir, f), "utf8");
    let inKanji = false;
    for (const line of text.split("\n")) {
      if (/^ {2}kanji:\s*$/.test(line)) { inKanji = true; continue; }
      const item = line.match(/^ {4}- (.+?)\s*$/);
      if (inKanji && item) { seen.add(item[1]); continue; }
      if (!/^\s*$/.test(line)) inKanji = false;
    }
  }
  return [...seen];
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchOne(character) {
  const res = await fetch(`${API}/${encodeURIComponent(character)}`);
  if (!res.ok) throw new Error(`${character}: HTTP ${res.status}`);
  return res.json();
}

/** YAML string quoting: only what this data can actually contain. */
function q(s) {
  return `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

async function build() {
  const characters = taughtCharacters();
  if (characters.length === 0) throw new Error("no kanji found in src/content/lessons — refusing to write an empty file");
  console.log(`building ${characters.length} kanji`);

  const entries = [];
  for (let i = 0; i < characters.length; i += BATCH) {
    const batch = characters.slice(i, i + BATCH);
    const details = await Promise.all(batch.map(fetchOne));
    for (const d of details) {
      entries.push({
        character: d.kanji,
        meanings: d.meanings.slice(0, 4),
        allMeanings: d.meanings,
        on: d.on_readings,
        kun: d.kun_readings,
        strokes: d.stroke_count ?? null,
      });
    }
    process.stdout.write(`  ${Math.min(i + BATCH, characters.length)}/${characters.length}\n`);
    if (i + BATCH < characters.length) await sleep(DELAY_MS);
  }

  const lines = [
    "# Generated by `node scripts/kanji.mjs build`. Do not edit.",
    "# Source: KANJIDIC2 via kanjiapi.dev. KANJIDIC2 is CC BY-SA 4.0,",
    "# (c) Electronic Dictionary Research and Development Group.",
    "",
  ];
  for (const e of entries) {
    lines.push(`- character: ${q(e.character)}`);
    lines.push(`  meanings: [${e.meanings.map(q).join(", ")}]`);
    lines.push(`  allMeanings: [${e.allMeanings.map(q).join(", ")}]`);
    lines.push(`  on: [${e.on.map(q).join(", ")}]`);
    lines.push(`  kun: [${e.kun.map(q).join(", ")}]`);
    lines.push(`  strokes: ${e.strokes === null ? "null" : e.strokes}`);
  }
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join("\n") + "\n");
  console.log(`wrote ${entries.length} entries to src/content/kanji/kanji.yaml`);
}

const KRAD = "https://raw.githubusercontent.com/hoffmannjp/krad-unicode/master/krad.json";

// krad-unicode stand-ins: glyphs it borrows for elements it has no codepoint
// for. 乞 stands for the unencoded 𠂉 (the slant over a level stroke atop 矢,
// 竹 and 攵) and appears in 14 of our kanji, none of which contain 乞 "beg";
// 隶 stands for 彔 in 緑. Rendering either would name a piece the kanji does
// not contain, and a learner would build a memory on it. Dropping them loses
// a true part of the kanji, which is better than showing a false one.
const STAND_INS = new Set(["乞", "隶"]);

// krad-unicode also lists an element that is right for other kanji but
// spurious for one host: 毋 is real in 毎 and 海 yet is 母's whole component
// row, which would read "mother is made of: do not"; ⺭ is real in 社 but in
// 杯 (木 + 不) it stands in for stroke groups. Global exclusion would break
// the legitimate uses, so these drop per kanji.
const PER_KANJI_DROP = { "母": ["毋"], "杯": ["⺭"] };
const DECOMP_OUT = join(ROOT, "src/content/kanji/decomposition.json");

async function decompose() {
  const characters = taughtCharacters();
  if (characters.length === 0) throw new Error("no kanji found in src/content/lessons — refusing to write an empty file");

  const res = await fetch(KRAD);
  if (!res.ok) throw new Error(`KRADFILE fetch failed: HTTP ${res.status}`);
  const raw = await res.json();
  const byLiteral = new Map(raw.map((e) => [e.literal, e.components]));

  const map = {};
  const missing = [];
  for (const c of characters) {
    const parts = byLiteral.get(c);
    if (parts === undefined) { missing.push(c); continue; }
    // Drop self-reference: KRADFILE gives 水 -> ["水"], and "水 is made of 水"
    // is noise. Such kanji end up with an empty list and render no row. The
    // stand-in glyphs above go the same way.
    const dropped = PER_KANJI_DROP[c] ?? [];
    map[c] = parts.filter((p) => p !== c && !STAND_INS.has(p) && !dropped.includes(p));
  }
  if (missing.length > 0) throw new Error(`not in KRADFILE: ${missing.join(" ")}`);

  const out = {
    _source: "KRADFILE via hoffmannjp/krad-unicode",
    _licence: "CC BY-SA 4.0, (c) James William Breen and The Electronic Dictionary Research and Development Group",
    map,
  };
  writeFileSync(DECOMP_OUT, JSON.stringify(out, null, 2) + "\n");

  const comps = new Set(Object.values(map).flat());
  const empty = Object.values(map).filter((v) => v.length === 0).length;
  console.log(`wrote ${Object.keys(map).length} entries to src/content/kanji/decomposition.json`);
  console.log(`  ${comps.size} distinct components, ${empty} kanji with no component row`);
}

/**
 * Advisory report for an author. Never exits non-zero: a lesson introducing a
 * kanji whose shapes are all new is a legitimate authoring choice, and
 * components never reorder lessons (spec decision 4).
 */
async function gaps() {
  const decomp = JSON.parse(readFileSync(DECOMP_OUT, "utf8")).map;
  const taught = new Set(Object.keys(decomp));

  console.log("# Kanji whose components are all new at introduction\n");
  const seen = new Set();
  const met = new Set();
  for (const c of taughtCharacters()) {
    const parts = decomp[c] ?? [];
    const known = parts.filter((p) => seen.has(p) || met.has(p));
    if (parts.length > 0 && known.length === 0) console.log(`  ${c} — ${parts.join(" ")}`);
    seen.add(c);
    for (const p of parts) met.add(p);
  }

  console.log("\n# Decompositions worth an author's eye\n");
  for (const [c, parts] of Object.entries(decomp)) {
    // KRADFILE is built for radical lookup, not teaching. Long lists and
    // near-duplicate parts (母 beside 毋) are where it misleads.
    if (parts.length >= 5) console.log(`  ${c} — ${parts.length} parts: ${parts.join(" ")}`);
  }

  const used = new Set(Object.values(decomp).flat());
  console.log(`\n# Totals\n`);
  console.log(`  ${taught.size} kanji, ${used.size} distinct components`);
  console.log(`  ${[...used].filter((g) => taught.has(g)).length} components are themselves taught kanji`);
  console.log(`  ${Object.values(decomp).filter((v) => v.length === 0).length} kanji render no component row`);
}

const cmd = process.argv[2];
if (cmd === "build") await build();
else if (cmd === "decompose") await decompose();
else if (cmd === "gaps") await gaps();
else { console.error(`usage: kanji.mjs build|decompose|gaps`); process.exit(1); }
