#!/usr/bin/env node
/**
 * Content manifest — everything the course already teaches, in one file.
 *
 *   node scripts/manifest.mjs         write data/content-manifest.json
 *   node scripts/manifest.mjs check   report collisions, exit 1 if any
 *
 * This exists because the most expensive mistake in content authoring is
 * teaching something twice. An author who cannot see the existing 484 words
 * proposes duplicates, and the schema validators do not catch it: parseWords
 * dedupes *within a file*, never across the concatenated pool. Two chapters
 * authored in parallel each add a clean file and the collision only surfaces
 * at integration.
 *
 * The manifest is committed and regenerated, like docs/book-one-ladder.md, so
 * an author (or an agent) can read it without running anything.
 *
 * `check` is the mechanical half. It finds what a reviewer reading two YAML
 * files side by side cannot: the same id in two files, and the same Japanese
 * word under two different ids.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ourWords, ourLessons } from "./jlpt.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "data/content-manifest.json");

/**
 * Entries from a content directory, line-based like ourWords().
 *
 * A top-level `- id:` opens an entry; its own fields sit at exactly two
 * spaces. Matching leading whitespace loosely would let a nested `example:`
 * block's `japanese:` overwrite the entry it belongs to — the same trap
 * ourWords() documents.
 */
function readEntries(dir, fields) {
  const path = join(ROOT, dir);
  const out = [];
  for (const file of readdirSync(path).filter((f) => f.endsWith(".yaml")).sort()) {
    let cur = null;
    for (const line of readFileSync(join(path, file), "utf8").split("\n")) {
      const id = line.match(/^-\s+id:\s*(\S+)/);
      if (id) {
        cur = { id: id[1], file };
        out.push(cur);
        continue;
      }
      if (cur === null) continue;
      for (const field of fields) {
        const m = line.match(new RegExp(`^ {2}${field}: *(.+?) *$`));
        if (m) cur[field] = m[1].replace(/^"|"$/g, "");
      }
    }
  }
  return out;
}

function build() {
  const words = ourWords();
  const phrases = readEntries("src/content/phrases", ["japanese", "reading", "english", "scenario", "jlpt"]);
  const grammar = readEntries("src/content/grammar", ["pattern", "gloss", "phraseId", "jlpt"]);
  const lessons = ourLessons();

  const kanji = new Set(lessons.flatMap((l) => l.kanji));

  return {
    generated: new Date().toISOString().slice(0, 10),
    note:
      "Generated by `node scripts/manifest.mjs`. Do not edit. " +
      "Everything the course already teaches: reuse these ids rather than authoring a duplicate.",
    counts: {
      words: words.length,
      phrases: phrases.length,
      grammar: grammar.length,
      lessons: lessons.length,
      kanji: kanji.size,
    },
    words,
    phrases,
    grammar,
    kanji: [...kanji],
  };
}

/**
 * The two collisions that ship silently.
 *
 * A duplicate id fails at integration, long after both authors have finished.
 * A duplicate headword under two ids never fails at all — it just teaches the
 * learner the same word twice under different names.
 */
function collisions(m) {
  const byId = new Map();
  const byWord = new Map();
  const push = (map, key, value) => {
    const list = map.get(key);
    if (list === undefined) map.set(key, [value]);
    else list.push(value);
  };

  for (const w of m.words) {
    push(byId, w.id, w.file);
    if (w.japanese !== undefined) push(byWord, `${w.japanese}|${w.reading ?? ""}`, `${w.id} (${w.file})`);
  }
  for (const p of m.phrases) push(byId, p.id, p.file);
  for (const g of m.grammar) push(byId, g.id, g.file);

  return {
    duplicateIds: [...byId].filter(([, f]) => f.length > 1).map(([id, files]) => ({ id, files })),
    duplicateWords: [...byWord].filter(([, e]) => e.length > 1).map(([key, entries]) => ({ word: key, entries })),
  };
}

/**
 * Guarded so the test can import build() and collisions() without the CLI
 * firing on import — the same trap scripts/kanji.mjs hit with an exported
 * helper on a top-level-await module.
 */
const runDirectly = process.argv[1] !== undefined && process.argv[1].endsWith("manifest.mjs");
const cmd = process.argv[2];

if (!runDirectly) {
  // imported for tests
} else if (cmd === undefined) {
  const m = build();
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, JSON.stringify(m, null, 1) + "\n");
  const c = m.counts;
  console.log(`wrote data/content-manifest.json`);
  console.log(`  ${c.words} words, ${c.phrases} phrases, ${c.grammar} patterns, ${c.kanji} kanji, ${c.lessons} lessons`);
} else if (cmd === "check") {
  const { duplicateIds, duplicateWords } = collisions(build());
  for (const { id, files } of duplicateIds) console.error(`duplicate id: ${id} in ${files.join(", ")}`);
  for (const { word, entries } of duplicateWords) console.error(`same word twice: ${word} as ${entries.join(" and ")}`);
  if (duplicateIds.length + duplicateWords.length === 0) {
    console.log("no collisions");
  } else {
    console.error(`\n${duplicateIds.length} duplicate id(s), ${duplicateWords.length} duplicate word(s)`);
    process.exit(1);
  }
} else {
  console.error("usage: manifest.mjs [check]");
  process.exit(1);
}

export { build, collisions };
